services:
  mysql:
    image: 'mysql:8.4.7'
    container_name: 'ihy_container'
    environment:
      - 'MYSQL_DATABASE=ihy'
      - 'MYSQL_PASSWORD=root'
      - 'MYSQL_ROOT_PASSWORD=root'
    ports:
      - '3306:3306'
    restart: 'unless-stopped'
