server:
  port: 8080
  servlet:
    context-path: /ihy

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/ihy"
    username: "root"
    password: "root"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  jpa:
    hibernate:
      ddl-auto: "update"
    show-sql: "true"
    database-platform: "org.hibernate.dialect.MySQL8Dialect"

jwt:
  signerKey: "ff1c36d96d625195bd74153d2e9480f2477fffe33bde5374664e501865d1ec5d"
  expiration: 60 #in hours
  refreshable: 120 #in hours